### ISSUE TITLE
Why not use curl?

### ISSUE THREAD

**Issue by stunna** [sgrodzicki/pagespeed#5]
Using this libary ends in slow requests with my setup.

it was faster to use curl.

**Comment by sgrodzicki** [comment]
These days it would probably be best to use an abstraction like [HTTPlug](http://httplug.io) so one could use their favorite HTTP client (e.g. cURL). Can you please share an example of your performance improvements with cURL (e.g. a [Blackfire](https://blackfire.io) profile)?

**Comment by stunna** [comment]
Not at the moment, I have to take some time to get familiar with this, thanks for the input.

**Comment by stunna** [comment]
i just switched to plain php and curl instead your libary and increased requests significant

![screenshot-console cloud google com-2017-09-24-16-50-19-230](https://user-images.githubusercontent.com/532363/30783774-0d58e86a-a149-11e7-9728-635cc1e97d22.png)
